fix: Update release and test workflows (#1)

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,22 +1,95 @@
-on: [push, pull_request]
-name: CI
+# This GitHub action runs your tests for each commit push and/or PR. Optionally
+# you can turn it on using a cron schedule for regular testing.
+#
+name: Tests
+on:
+  pull_request:
+    paths-ignore:
+      - 'README.md'
+  push:
+    branches:
+      - main
 jobs:
-  tests:
+  # ensure the code builds...
+  build:
+    name: Build
     runs-on: ubuntu-latest
-    env:
-      GO111MODULE: on
+    timeout-minutes: 5
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-    - name: Format
-      run: go fmt ./...
-    - name: Build
-      run: go build ./...
-    - name: Vet
-      run: go vet ./...
-    - name: Test
-      uses: cedrickring/golang-action@master
-      with:
-        args: make test
-    - name: Secure
-      run: make secure
+
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v3
+
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version-file: 'go.mod'
+          cache: true
+        id: go
+
+      - name: Get dependencies
+        run: |
+          go mod download
+
+      - name: Build
+        run: |
+          go build -v .
+
+  generate:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-go@v3
+        with:
+          go-version-file: 'go.mod'
+          cache: true
+      - run: go generate ./...
+      - name: git diff
+        run: |
+          git diff --compact-summary --exit-code || \
+            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
+
+  # run acceptance tests in a matrix with Terraform core versions
+  test:
+    name: Matrix Test
+    needs: build
+    runs-on: ubuntu-latest
+    timeout-minutes: 15
+#    strategy: - Disable acceptance testing for now
+#      fail-fast: false
+#      matrix:
+#        # list whatever Terraform versions here you would like to support
+#        terraform:
+#          - '1.0.*'
+#          - '1.1.*'
+    steps:
+
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v3
+
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version-file: 'go.mod'
+          cache: true
+        id: go
+
+#      - uses: hashicorp/setup-terraform@v2 - Disable acceptance testing for now
+#        with:
+#          terraform_version: ${{ matrix.terraform }}
+#          terraform_wrapper: false
+
+      - name: Get dependencies
+        run: |
+          go mod download
+
+      - name: TF acceptance tests
+        timeout-minutes: 10
+        env:
+          #TF_ACC: "1" - Disable acceptance testing for now
+          ONELOGIN_CLIENT_ID: "a-client-id"
+          ONELOGIN_CLIENT_SECRET: "a-client-secret"
+          ONELOGIN_OAPI_URL: "an-oapi-url"
+
+        run: |
+          go test -v -cover ./...
